# Generated by Django 4.2.1 on 2023-05-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0002_opening_alter_candidate_email_alter_candidate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='candidate_collection',
        ),
        migrations.AddField(
            model_name='candidate',
            name='opening',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Resume_Collect.opening'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.TextField(null=True),
        ),
    ]
