# Generated by Django 4.2.1 on 2023-05-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0003_remove_opening_candidate_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='opening',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Resume_Collect.opening'),
        ),
    ]
