# Generated by Django 4.2.1 on 2023-05-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0004_alter_candidate_opening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='opening',
        ),
    ]
