# Generated by Django 4.2.1 on 2023-05-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0005_remove_candidate_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='opening',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Resume_Collect.opening'),
        ),
    ]
