# Generated by Django 4.2.1 on 2023-05-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0007_remove_candidate_opening_delete_opening'),
    ]

    operations = [
    ]
