# Generated by Django 4.2.1 on 2023-05-29 12:35

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0013_remove_candidate_opening_delete_opening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
