# Generated by Django 4.2.1 on 2023-05-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0015_candidate_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
