# Generated by Django 4.2.1 on 2023-05-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0016_opening_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='description',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
