# Generated by Django 4.2.1 on 2023-06-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0017_remove_opening_description_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default=None, upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
