# Generated by Django 4.2.1 on 2023-06-02 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0018_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Resume_Collect.opening'),
        ),
    ]
