# Generated by Django 4.2.1 on 2023-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0023_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to='static/resumes/'),
        ),
    ]
