# Generated by Django 4.2.1 on 2023-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_Collect', '0024_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to='Resume_Collect/static/resumes/'),
        ),
    ]
